version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    build:
      context: ./producer
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      RABBITMQ_HOST: rabbitmq
  
  consumer:
    build:
      context: ./consumer
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    environment:
      RABBITMQ_HOST: rabbitmq
